#include "openst/common/buildinfo.h"

#define OPENST_BUILDINFO_UNDEFINED "UNDEFINED"

#ifdef BUILDINFO_C_COMPILER
    #define M_OPENST_BUILDINFO_C_COMPILER BUILDINFO_C_COMPILER
#else
    #define M_OPENST_BUILDINFO_C_COMPILER OPENST_BUILDINFO_UNDEFINED
#endif

#ifdef BUILDINFO_C_COMPILER_ID
    #define M_OPENST_BUILDINFO_C_COMPILER_ID BUILDINFO_C_COMPILER_ID
#else
    #define M_OPENST_BUILDINFO_C_COMPILER_ID OPENST_BUILDINFO_UNDEFINED
#endif

#ifdef BUILDINFO_C_COMPILER_VERSION
    #define M_OPENST_BUILDINFO_C_COMPILER_VERSION BUILDINFO_C_COMPILER_VERSION
#else
    #define M_OPENST_BUILDINFO_C_COMPILER_VERSION OPENST_BUILDINFO_UNDEFINED
#endif

#ifdef BUILDINFO_C_FLAGS
    #define M_OPENST_BUILDINFO_C_FLAGS BUILDINFO_C_FLAGS
#else
    #define M_OPENST_BUILDINFO_C_FLAGS OPENST_BUILDINFO_UNDEFINED
#endif

#if defined(OPENST_SHARED_EXPORTS)
	#define M_OPENST_BUILDINFO_LINK_TYPE "SHARED"
#else
	#define M_OPENST_BUILDINFO_LINK_TYPE "STATIC"
#endif

#ifdef OPENST_FLOAT_PRECISION_SINGLE
    #define M_OPENST_BUILDINFO_FLOAT_PRECISION "single"
#else
    #define M_OPENST_BUILDINFO_FLOAT_PRECISION "double"
#endif

const char OPENST_BUILDINFO_C_COMPILER_STATIC[] = M_OPENST_BUILDINFO_C_COMPILER;
const char OPENST_BUILDINFO_C_COMPILER_ID_STATIC[] = M_OPENST_BUILDINFO_C_COMPILER_ID;
const char OPENST_BUILDINFO_C_COMPILER_VERSION_STATIC[] = M_OPENST_BUILDINFO_C_COMPILER_VERSION;
const char OPENST_BUILDINFO_C_FLAGS_STATIC[] = M_OPENST_BUILDINFO_C_FLAGS;
const char OPENST_BUILDINFO_LINK_TYPE_STATIC[] = M_OPENST_BUILDINFO_LINK_TYPE;
const char OPENST_BUILDINFO_FLOAT_PRECISION_STATIC[] = M_OPENST_BUILDINFO_FLOAT_PRECISION;

#define M_OPENST_BUILDINFO_STR_FULL \
    "OPENST_BUILDINFO_LINK_TYPE: " M_OPENST_BUILDINFO_LINK_TYPE "\n"\
    "OPENST_BUILDINFO_FLOAT_PRECISION: " M_OPENST_BUILDINFO_FLOAT_PRECISION "\n"\
    "OPENST_BUILDINFO_C_COMPILER: " M_OPENST_BUILDINFO_C_COMPILER "\n"\
    "OPENST_BUILDINFO_C_COMPILER_ID: " M_OPENST_BUILDINFO_C_COMPILER_ID "\n"\
    "OPENST_BUILDINFO_C_COMPILER_VERSION: " M_OPENST_BUILDINFO_C_COMPILER_VERSION "\n"\
    "OPENST_BUILDINFO_C_FLAGS: " M_OPENST_BUILDINFO_C_FLAGS "\n"

const char OPENST_BUILDINFO_STR_FULL_STATIC[] = M_OPENST_BUILDINFO_STR_FULL;
