#ifndef OPENST_COMMON_ERROR_H
#define OPENST_COMMON_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum OPENST_ERR_enum{
    OPENST_ERR_SUCCESS = 0,
    OPENST_ERR_ALG_GENERIC,
    OPENST_ERR_ALG_OUT_OF_BOUNDS,
    OPENST_ERR_ALG_TERMINATED,
    OPENST_ERR_ALG_INFINITE_LOOP,
    OPENST_ERR_UNDEFINED,
    OPENST_ERR_MEMORY_ALLOC,
    OPENST_ERR_PARAM_INVALID,
    OPENST_ERR_TYPE_CONVERSION,
    OPENST_ERR_DIV_BY_ZERO
} OPENST_ERR;

#ifdef __cplusplus
}
#endif

#endif /* OPENST_COMMON_ERROR_H */
